services:
  mysql:
    image: mysql:8.4
    container_name: shoplane-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ecomDB
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - shoplane-mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 30s

  redis:
    image: redis:7.4-alpine
    container_name: shoplane-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  payment-gateway:
    image: devansh1709/shoplane-payment-gateway:latest
    container_name: shoplane-payment-gateway
    restart: unless-stopped

    ports:
      - "8081:8081"

    environment:
      DB_URL: jdbc:mysql://mysql:3306/pay
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}

    depends_on:
      mysql:
        condition: service_healthy

  ecommerce-backend:
    image: devansh1709/shoplane-backend:latest
    container_name: shoplane-ecommerce-backend
    restart: unless-stopped

    ports:
      - "8090:8080"

    environment:
      DB_URL: jdbc:mysql://mysql:3306/ecomDB
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}

      REDIS_HOST: redis
      REDIS_PORT: 6379

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}

      PAYMENT_GATEWAY_URL: http://payment-gateway:8081

      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_APP_PASSWORD: ${MAIL_APP_PASSWORD}

    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      payment-gateway:
        condition: service_started

volumes:
  shoplane-mysql: